// <auto-generated />
using System;
using Cherry.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cherry.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718140000_CompactCatalog")]
    partial class CompactCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cherry.Domain.Entities.DurableBatchReceipt", b =>
                {
                    b.Property<string>("CrawlerId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("crawler_id");

                    b.Property<long>("Epoch")
                        .HasColumnType("bigint")
                        .HasColumnName("epoch");

                    b.Property<int>("LastAccepted")
                        .HasColumnType("integer")
                        .HasColumnName("last_accepted");

                    b.Property<int>("LastDuplicates")
                        .HasColumnType("integer")
                        .HasColumnName("last_duplicates");

                    b.Property<long>("LastEndSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_end_sequence");

                    b.Property<string>("LastPayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_payload_sha256");

                    b.Property<long>("LastStartSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_start_sequence");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("CrawlerId", "Epoch");

                    b.ToTable("durable_batch_receipts", null, t =>
                        {
                            t.HasCheckConstraint("CK_durable_batch_receipts_epoch", "epoch > 0");

                            t.HasCheckConstraint("CK_durable_batch_receipts_state", "(last_start_sequence = 0 AND last_end_sequence = 0 AND last_payload_sha256 = '' AND last_accepted = 0 AND last_duplicates = 0) OR (last_start_sequence > 0 AND last_end_sequence >= last_start_sequence AND char_length(last_payload_sha256) = 64 AND last_accepted >= 0 AND last_duplicates >= 0)");
                        });
                });

            modelBuilder.Entity("Cherry.Domain.Entities.MetadataDecision", b =>
                {
                    b.Property<byte[]>("InfoHash")
                        .HasColumnType("bytea")
                        .HasColumnName("info_hash");

                    b.Property<short>("DecisionCode")
                        .HasColumnType("smallint")
                        .HasColumnName("decision_code");

                    b.HasKey("InfoHash");

                    b.ToTable("metadata_decisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_metadata_decisions_code", "decision_code BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_metadata_decisions_info_hash", "octet_length(info_hash) = 20");
                        });
                });

            modelBuilder.Entity("Cherry.Domain.Entities.SearchOutboxItem", b =>
                {
                    b.Property<long>("TorrentId")
                        .HasColumnType("bigint")
                        .HasColumnName("torrent_id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("AvailableAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("EnqueuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueued_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint")
                        .HasColumnName("generation");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("last_error");

                    b.Property<Guid?>("LeaseOwner")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_owner");

                    b.Property<DateTime?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("TorrentId");

                    b.HasIndex("AvailableAt", "LeaseUntil")
                        .HasDatabaseName("idx_search_outbox_due");

                    b.ToTable("search_outbox", null, t =>
                        {
                            t.HasCheckConstraint("CK_search_outbox_attempts", "attempt_count >= 0");

                            t.HasCheckConstraint("CK_search_outbox_generation", "generation > 0");

                            t.HasCheckConstraint("CK_search_outbox_lease", "(lease_owner IS NULL AND lease_until IS NULL) OR (lease_owner IS NOT NULL AND lease_until IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Cherry.Domain.Entities.Torrent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("FileCount")
                        .HasColumnType("integer")
                        .HasColumnName("file_count");

                    b.Property<byte[]>("InfoHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("info_hash");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("TotalLength")
                        .HasColumnType("bigint")
                        .HasColumnName("total_length");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_torrents_created");

                    b.HasIndex("InfoHash")
                        .IsUnique()
                        .HasDatabaseName("ux_torrents_info_hash");

                    b.ToTable("torrents", null, t =>
                        {
                            t.HasCheckConstraint("CK_torrents_info_hash", "octet_length(info_hash) = 20");
                        });
                });

            modelBuilder.Entity("Cherry.Domain.Entities.TorrentExtensionSummary", b =>
                {
                    b.Property<long>("TorrentId")
                        .HasColumnType("bigint")
                        .HasColumnName("torrent_id");

                    b.Property<string>("Extension")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("extension");

                    b.Property<int>("FileCount")
                        .HasColumnType("integer")
                        .HasColumnName("file_count");

                    b.Property<long>("TotalLength")
                        .HasColumnType("bigint")
                        .HasColumnName("total_length");

                    b.HasKey("TorrentId", "Extension");

                    b.ToTable("torrent_extension_summaries", (string)null);
                });

            modelBuilder.Entity("Cherry.Domain.Entities.TorrentFile", b =>
                {
                    b.Property<long>("Length")
                        .HasColumnType("bigint")
                        .HasColumnName("length");

                    b.Property<string>("PathText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path_text");

                    b.Property<long>("TorrentId")
                        .HasColumnType("bigint")
                        .HasColumnName("torrent_id");

                    b.HasIndex("TorrentId")
                        .HasDatabaseName("idx_torrent_files_torrent_id");

                    b.ToTable("torrent_files", (string)null);
                });

            modelBuilder.Entity("Cherry.Domain.Entities.TorrentRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("info_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("InfoHash")
                        .HasDatabaseName("idx_torrent_requests_hash");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_torrent_requests_status");

                    b.ToTable("torrent_requests", (string)null);
                });

            modelBuilder.Entity("Cherry.Domain.Entities.SearchOutboxItem", b =>
                {
                    b.HasOne("Cherry.Domain.Entities.Torrent", null)
                        .WithMany()
                        .HasForeignKey("TorrentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cherry.Domain.Entities.TorrentExtensionSummary", b =>
                {
                    b.HasOne("Cherry.Domain.Entities.Torrent", null)
                        .WithMany()
                        .HasForeignKey("TorrentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cherry.Domain.Entities.TorrentFile", b =>
                {
                    b.HasOne("Cherry.Domain.Entities.Torrent", null)
                        .WithMany()
                        .HasForeignKey("TorrentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
