using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Cherry.Infrastructure.Data.Migrations;

/// <summary>
/// Rebuilds the catalog around a compact surrogate key. The migration copies
/// every authoritative/search/detail row before dropping the wide legacy
/// tables, so an upgrade never relies on lossy in-place casts or default IDs.
/// </summary>
public partial class CompactCatalog : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            LOCK TABLE torrents, torrent_files, torrent_extension_summaries,
                       metadata_decisions, rejected_hashes, search_outbox
                IN ACCESS EXCLUSIVE MODE;

            ALTER TABLE search_outbox
                DROP CONSTRAINT "FK_search_outbox_torrents_info_hash";

            ALTER TABLE torrents RENAME TO torrents_legacy;
            ALTER TABLE torrent_files RENAME TO torrent_files_legacy;
            ALTER TABLE torrent_extension_summaries RENAME TO torrent_extension_summaries_legacy;
            ALTER TABLE metadata_decisions RENAME TO metadata_decisions_legacy;
            ALTER TABLE rejected_hashes RENAME TO rejected_hashes_legacy;
            ALTER TABLE search_outbox RENAME TO search_outbox_legacy;

            CREATE TABLE torrents (
                id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                info_hash bytea NOT NULL,
                name text NOT NULL,
                total_length bigint NOT NULL,
                file_count integer NOT NULL,
                created_at timestamp with time zone NOT NULL DEFAULT NOW(),
                CONSTRAINT torrents_compact_pkey PRIMARY KEY (id),
                CONSTRAINT "CK_torrents_info_hash" CHECK (octet_length(info_hash) = 20));

            CREATE TABLE torrent_files (
                torrent_id bigint NOT NULL,
                path_text text NOT NULL,
                length bigint NOT NULL);

            CREATE TABLE torrent_extension_summaries (
                torrent_id bigint NOT NULL,
                extension character varying(32) NOT NULL,
                file_count integer NOT NULL,
                total_length bigint NOT NULL,
                CONSTRAINT torrent_extension_summaries_compact_pkey
                    PRIMARY KEY (torrent_id, extension));

            CREATE TABLE metadata_decisions (
                info_hash bytea NOT NULL,
                decision_code smallint NOT NULL,
                CONSTRAINT metadata_decisions_compact_pkey PRIMARY KEY (info_hash),
                CONSTRAINT "CK_metadata_decisions_info_hash"
                    CHECK (octet_length(info_hash) = 20),
                CONSTRAINT "CK_metadata_decisions_code"
                    CHECK (decision_code BETWEEN 1 AND 5));

            CREATE TABLE search_outbox (
                torrent_id bigint NOT NULL,
                generation bigint NOT NULL,
                enqueued_at timestamp with time zone NOT NULL DEFAULT NOW(),
                available_at timestamp with time zone NOT NULL DEFAULT NOW(),
                lease_owner uuid NULL,
                lease_until timestamp with time zone NULL,
                attempt_count integer NOT NULL DEFAULT 0,
                last_error character varying(1024) NULL,
                updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
                CONSTRAINT search_outbox_compact_pkey PRIMARY KEY (torrent_id),
                CONSTRAINT "CK_search_outbox_generation" CHECK (generation > 0),
                CONSTRAINT "CK_search_outbox_attempts" CHECK (attempt_count >= 0),
                CONSTRAINT "CK_search_outbox_lease" CHECK (
                    (lease_owner IS NULL AND lease_until IS NULL) OR
                    (lease_owner IS NOT NULL AND lease_until IS NOT NULL)));

            INSERT INTO torrents (info_hash, name, total_length, file_count, created_at)
            SELECT decode(info_hash, 'hex'), name, total_length, file_count, created_at
              FROM torrents_legacy
             ORDER BY info_hash;

            INSERT INTO torrent_files (torrent_id, path_text, length)
            SELECT torrent.id, file.path_text, file.length
              FROM torrent_files_legacy AS file
              JOIN torrents AS torrent
                ON torrent.info_hash = decode(file.info_hash, 'hex');

            INSERT INTO torrent_extension_summaries (
                torrent_id, extension, file_count, total_length)
            SELECT torrent.id, summary.extension, summary.file_count, summary.total_length
              FROM torrent_extension_summaries_legacy AS summary
              JOIN torrents AS torrent
                ON torrent.info_hash = decode(summary.info_hash, 'hex');

            INSERT INTO metadata_decisions (info_hash, decision_code)
            SELECT decision.info_hash,
                   CASE
                       WHEN decision.action = 1 AND decision.reason = 'hash_only_file_cap' THEN 3
                       WHEN decision.action = 2 AND decision.reason = 'reject_file_cap' THEN 4
                       WHEN decision.action = 1 AND decision.reason = 'invalid_normalized_metadata' THEN 5
                       WHEN decision.action = 2 THEN 2
                       ELSE 1
                   END
              FROM metadata_decisions_legacy AS decision
             WHERE NOT EXISTS (
                       SELECT 1 FROM torrents
                        WHERE torrents.info_hash = decision.info_hash)
            ON CONFLICT (info_hash) DO NOTHING;

            INSERT INTO metadata_decisions (info_hash, decision_code)
            SELECT rejected.info_hash, 2
              FROM rejected_hashes_legacy AS rejected
             WHERE NOT EXISTS (
                       SELECT 1 FROM torrents
                        WHERE torrents.info_hash = rejected.info_hash)
            ON CONFLICT (info_hash) DO UPDATE
                SET decision_code = 2
              WHERE metadata_decisions.decision_code NOT IN (2, 4);

            INSERT INTO search_outbox (
                torrent_id, generation, enqueued_at, available_at,
                lease_owner, lease_until, attempt_count, last_error, updated_at)
            SELECT torrent.id, item.generation, item.enqueued_at, item.available_at,
                   item.lease_owner, item.lease_until, item.attempt_count,
                   item.last_error, item.updated_at
              FROM search_outbox_legacy AS item
              JOIN torrents AS torrent
                ON torrent.info_hash = decode(item.info_hash, 'hex');

            DROP TABLE search_outbox_legacy;
            DROP TABLE torrent_extension_summaries_legacy;
            DROP TABLE torrent_files_legacy;
            DROP TABLE metadata_decisions_legacy;
            DROP TABLE rejected_hashes_legacy;
            DROP TABLE torrents_legacy;

            ALTER TABLE torrents
                RENAME CONSTRAINT torrents_compact_pkey TO "PK_torrents";
            ALTER TABLE torrent_extension_summaries
                RENAME CONSTRAINT torrent_extension_summaries_compact_pkey
                TO "PK_torrent_extension_summaries";
            ALTER TABLE metadata_decisions
                RENAME CONSTRAINT metadata_decisions_compact_pkey TO "PK_metadata_decisions";
            ALTER TABLE search_outbox
                RENAME CONSTRAINT search_outbox_compact_pkey TO "PK_search_outbox";

            CREATE UNIQUE INDEX ux_torrents_info_hash ON torrents (info_hash);
            CREATE INDEX idx_torrents_created ON torrents (created_at);
            CREATE INDEX idx_torrent_files_torrent_id ON torrent_files (torrent_id);
            CREATE INDEX idx_search_outbox_due ON search_outbox (available_at, lease_until);

            ALTER TABLE torrent_files
                ADD CONSTRAINT "FK_torrent_files_torrents_torrent_id"
                FOREIGN KEY (torrent_id) REFERENCES torrents (id) ON DELETE CASCADE;
            ALTER TABLE torrent_extension_summaries
                ADD CONSTRAINT "FK_torrent_extension_summaries_torrents_torrent_id"
                FOREIGN KEY (torrent_id) REFERENCES torrents (id) ON DELETE CASCADE;
            ALTER TABLE search_outbox
                ADD CONSTRAINT "FK_search_outbox_torrents_torrent_id"
                FOREIGN KEY (torrent_id) REFERENCES torrents (id) ON DELETE CASCADE;

            ANALYZE torrents;
            ANALYZE torrent_files;
            ANALYZE torrent_extension_summaries;
            ANALYZE metadata_decisions;
            ANALYZE search_outbox;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            LOCK TABLE torrents, torrent_files, torrent_extension_summaries,
                       metadata_decisions, search_outbox
                IN ACCESS EXCLUSIVE MODE;

            ALTER TABLE torrent_files
                DROP CONSTRAINT "FK_torrent_files_torrents_torrent_id";
            ALTER TABLE torrent_extension_summaries
                DROP CONSTRAINT "FK_torrent_extension_summaries_torrents_torrent_id";
            ALTER TABLE search_outbox
                DROP CONSTRAINT "FK_search_outbox_torrents_torrent_id";

            ALTER TABLE torrent_files ADD COLUMN info_hash character varying(40);
            ALTER TABLE torrent_extension_summaries ADD COLUMN info_hash character varying(40);
            ALTER TABLE search_outbox ADD COLUMN info_hash character varying(40);

            UPDATE torrent_files AS file
               SET info_hash = encode(torrent.info_hash, 'hex')
              FROM torrents AS torrent
             WHERE torrent.id = file.torrent_id;
            UPDATE torrent_extension_summaries AS summary
               SET info_hash = encode(torrent.info_hash, 'hex')
              FROM torrents AS torrent
             WHERE torrent.id = summary.torrent_id;
            UPDATE search_outbox AS item
               SET info_hash = encode(torrent.info_hash, 'hex')
              FROM torrents AS torrent
             WHERE torrent.id = item.torrent_id;

            ALTER TABLE torrent_files ALTER COLUMN info_hash SET NOT NULL;
            ALTER TABLE torrent_extension_summaries ALTER COLUMN info_hash SET NOT NULL;
            ALTER TABLE search_outbox ALTER COLUMN info_hash SET NOT NULL;

            DROP INDEX idx_torrent_files_torrent_id;
            DROP INDEX idx_search_outbox_due;
            ALTER TABLE torrent_extension_summaries
                DROP CONSTRAINT "PK_torrent_extension_summaries";
            ALTER TABLE search_outbox DROP CONSTRAINT "PK_search_outbox";

            ALTER TABLE torrent_files DROP COLUMN torrent_id;
            ALTER TABLE torrent_extension_summaries DROP COLUMN torrent_id;
            ALTER TABLE search_outbox DROP COLUMN torrent_id;

            DROP INDEX idx_torrents_created;
            DROP INDEX ux_torrents_info_hash;
            ALTER TABLE torrents DROP CONSTRAINT "PK_torrents";
            ALTER TABLE torrents DROP CONSTRAINT "CK_torrents_info_hash";
            ALTER TABLE torrents
                ALTER COLUMN info_hash TYPE character varying(40)
                USING encode(info_hash, 'hex');
            ALTER TABLE torrents ADD COLUMN piece_length integer NOT NULL DEFAULT 0;
            ALTER TABLE torrents ADD COLUMN is_private boolean NOT NULL DEFAULT false;
            ALTER TABLE torrents ADD COLUMN source character varying(32);
            ALTER TABLE torrents ADD COLUMN policy_id character varying(256);
            ALTER TABLE torrents ADD COLUMN region character varying(64);
            ALTER TABLE torrents ADD COLUMN retained_level smallint NOT NULL DEFAULT 3;
            ALTER TABLE torrents ADD COLUMN needs_refetch boolean NOT NULL DEFAULT false;
            ALTER TABLE torrents ADD COLUMN peer_count integer NOT NULL DEFAULT 0;
            ALTER TABLE torrents ADD COLUMN peer_updated_at timestamp with time zone;
            ALTER TABLE torrents ADD COLUMN updated_at timestamp with time zone NOT NULL DEFAULT NOW();
            ALTER TABLE torrents DROP COLUMN id;
            ALTER TABLE torrents ADD CONSTRAINT "PK_torrents" PRIMARY KEY (info_hash);
            ALTER TABLE torrents ADD CONSTRAINT "CK_torrents_retained_level"
                CHECK (retained_level IN (2, 3));
            ALTER TABLE torrents ADD CONSTRAINT "CK_torrents_refetch"
                CHECK (retained_level = 2 OR NOT needs_refetch);
            CREATE INDEX idx_torrents_created ON torrents (created_at);
            CREATE INDEX idx_torrents_peer_count ON torrents (peer_count);

            ALTER TABLE torrent_extension_summaries
                ADD CONSTRAINT "PK_torrent_extension_summaries"
                PRIMARY KEY (info_hash, extension);
            ALTER TABLE search_outbox
                ADD CONSTRAINT "PK_search_outbox" PRIMARY KEY (info_hash);
            CREATE INDEX idx_torrent_files_info_hash ON torrent_files (info_hash);
            CREATE INDEX idx_search_outbox_due ON search_outbox (available_at, lease_until);
            ALTER TABLE search_outbox
                ADD CONSTRAINT "FK_search_outbox_torrents_info_hash"
                FOREIGN KEY (info_hash) REFERENCES torrents (info_hash) ON DELETE CASCADE;

            ALTER TABLE metadata_decisions DROP CONSTRAINT "CK_metadata_decisions_code";
            ALTER TABLE metadata_decisions ADD COLUMN action smallint;
            ALTER TABLE metadata_decisions ADD COLUMN retained_level smallint NOT NULL DEFAULT 1;
            ALTER TABLE metadata_decisions ADD COLUMN needs_refetch boolean NOT NULL DEFAULT false;
            ALTER TABLE metadata_decisions ADD COLUMN policy_id character varying(256);
            ALTER TABLE metadata_decisions ADD COLUMN reason character varying(1024);
            ALTER TABLE metadata_decisions ADD COLUMN first_seen timestamp with time zone;
            ALTER TABLE metadata_decisions ADD COLUMN region character varying(64);
            ALTER TABLE metadata_decisions ADD COLUMN updated_at timestamp with time zone NOT NULL DEFAULT NOW();
            UPDATE metadata_decisions
               SET action = CASE WHEN decision_code IN (2, 4) THEN 2 ELSE 1 END,
                   reason = CASE decision_code
                       WHEN 3 THEN 'hash_only_file_cap'
                       WHEN 4 THEN 'reject_file_cap'
                       WHEN 5 THEN 'invalid_normalized_metadata'
                       WHEN 2 THEN 'compact_reject'
                       ELSE 'compact_hash_only'
                   END;
            ALTER TABLE metadata_decisions ALTER COLUMN action SET NOT NULL;
            ALTER TABLE metadata_decisions ALTER COLUMN reason SET NOT NULL;

            CREATE TABLE rejected_hashes (
                info_hash bytea NOT NULL,
                CONSTRAINT "PK_rejected_hashes" PRIMARY KEY (info_hash),
                CONSTRAINT "CK_rejected_hashes_sha1_length"
                    CHECK (octet_length(info_hash) = 20));
            INSERT INTO rejected_hashes (info_hash)
            SELECT info_hash FROM metadata_decisions WHERE decision_code IN (2, 4);

            ALTER TABLE metadata_decisions DROP COLUMN decision_code;
            ALTER TABLE metadata_decisions ADD CONSTRAINT "CK_metadata_decisions_action"
                CHECK (action IN (1, 2));
            ALTER TABLE metadata_decisions ADD CONSTRAINT "CK_metadata_decisions_retained_level"
                CHECK (retained_level = 1);
            ALTER TABLE metadata_decisions ADD CONSTRAINT "CK_metadata_decisions_refetch"
                CHECK (action = 1 OR NOT needs_refetch);
            """);
    }
}
