// <auto-generated />
using System;
using Cherry.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cherry.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cherry.Domain.Entities.DurableBatchReceipt", b =>
                {
                    b.Property<string>("CrawlerId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("crawler_id");

                    b.Property<long>("Epoch")
                        .HasColumnType("bigint")
                        .HasColumnName("epoch");

                    b.Property<int>("LastAccepted")
                        .HasColumnType("integer")
                        .HasColumnName("last_accepted");

                    b.Property<int>("LastDuplicates")
                        .HasColumnType("integer")
                        .HasColumnName("last_duplicates");

                    b.Property<long>("LastEndSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_end_sequence");

                    b.Property<string>("LastPayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_payload_sha256");

                    b.Property<long>("LastStartSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_start_sequence");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("CrawlerId", "Epoch");

                    b.ToTable("durable_batch_receipts", null, t =>
                        {
                            t.HasCheckConstraint("CK_durable_batch_receipts_epoch", "epoch > 0");

                            t.HasCheckConstraint("CK_durable_batch_receipts_state", "(last_start_sequence = 0 AND last_end_sequence = 0 AND last_payload_sha256 = '' AND last_accepted = 0 AND last_duplicates = 0) OR (last_start_sequence > 0 AND last_end_sequence >= last_start_sequence AND char_length(last_payload_sha256) = 64 AND last_accepted >= 0 AND last_duplicates >= 0)");
                        });
                });

            modelBuilder.Entity("Cherry.Domain.Entities.MetadataDecision", b =>
                {
                    b.Property<byte[]>("InfoHash")
                        .HasColumnType("bytea")
                        .HasColumnName("info_hash");

                    b.Property<short>("Action")
                        .HasColumnType("smallint")
                        .HasColumnName("action");

                    b.Property<DateTime?>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<bool>("NeedsRefetch")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_refetch");

                    b.Property<string>("PolicyId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("policy_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("reason");

                    b.Property<string>("Region")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("region");

                    b.Property<short>("RetainedLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("retained_level");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("InfoHash");

                    b.ToTable("metadata_decisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_metadata_decisions_action", "action IN (1, 2)");

                            t.HasCheckConstraint("CK_metadata_decisions_info_hash", "octet_length(info_hash) = 20");

                            t.HasCheckConstraint("CK_metadata_decisions_refetch", "action = 1 OR NOT needs_refetch");

                            t.HasCheckConstraint("CK_metadata_decisions_retained_level", "retained_level = 1");
                        });
                });

            modelBuilder.Entity("Cherry.Domain.Entities.Torrent", b =>
                {
                    b.Property<string>("InfoHash")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("info_hash");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("FileCount")
                        .HasColumnType("integer")
                        .HasColumnName("file_count");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("NeedsRefetch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("needs_refetch");

                    b.Property<int>("PeerCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("peer_count");

                    b.Property<DateTime?>("PeerUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("peer_updated_at");

                    b.Property<int>("PieceLength")
                        .HasColumnType("integer")
                        .HasColumnName("piece_length");

                    b.Property<string>("PolicyId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("policy_id");

                    b.Property<string>("Region")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("region");

                    b.Property<short>("RetainedLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)3)
                        .HasColumnName("retained_level");

                    b.Property<string>("Source")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<long>("TotalLength")
                        .HasColumnType("bigint")
                        .HasColumnName("total_length");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("InfoHash");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_torrents_created");

                    b.HasIndex("PeerCount")
                        .HasDatabaseName("idx_torrents_peer_count");

                    b.ToTable("torrents", null, t =>
                        {
                            t.HasCheckConstraint("CK_torrents_refetch", "retained_level = 2 OR NOT needs_refetch");

                            t.HasCheckConstraint("CK_torrents_retained_level", "retained_level IN (2, 3)");
                        });
                });

            modelBuilder.Entity("Cherry.Domain.Entities.TorrentExtensionSummary", b =>
                {
                    b.Property<string>("InfoHash")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("info_hash");

                    b.Property<string>("Extension")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("extension");

                    b.Property<int>("FileCount")
                        .HasColumnType("integer")
                        .HasColumnName("file_count");

                    b.Property<long>("TotalLength")
                        .HasColumnType("bigint")
                        .HasColumnName("total_length");

                    b.HasKey("InfoHash", "Extension");

                    b.ToTable("torrent_extension_summaries", (string)null);
                });

            modelBuilder.Entity("Cherry.Domain.Entities.TorrentFile", b =>
                {
                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("info_hash");

                    b.Property<long>("Length")
                        .HasColumnType("bigint")
                        .HasColumnName("length");

                    b.Property<string>("PathText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path_text");

                    b.HasIndex("InfoHash")
                        .HasDatabaseName("idx_torrent_files_info_hash");

                    b.ToTable("torrent_files", (string)null);
                });

            modelBuilder.Entity("Cherry.Domain.Entities.TorrentRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("info_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("InfoHash")
                        .HasDatabaseName("idx_torrent_requests_hash");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_torrent_requests_status");

                    b.ToTable("torrent_requests", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
