// <auto-generated />
using System;
using Cherry.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cherry.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cherry.Domain.Entities.Torrent", b =>
                {
                    b.Property<string>("InfoHash")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("info_hash");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("FileCount")
                        .HasColumnType("integer")
                        .HasColumnName("file_count");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PeerCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("peer_count");

                    b.Property<DateTime>("PeerUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("peer_updated_at");

                    b.Property<int>("PieceLength")
                        .HasColumnType("integer")
                        .HasColumnName("piece_length");

                    b.Property<string>("Source")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<long>("TotalLength")
                        .HasColumnType("bigint")
                        .HasColumnName("total_length");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("InfoHash");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_torrents_created");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_torrents_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("PeerCount")
                        .HasDatabaseName("idx_torrents_peer_count");

                    b.ToTable("torrents", (string)null);
                });

            modelBuilder.Entity("Cherry.Domain.Entities.TorrentFile", b =>
                {
                    b.Property<string>("InfoHash")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("info_hash");

                    b.Property<string>("PathText")
                        .HasColumnType("text")
                        .HasColumnName("path_text");

                    b.Property<long>("Length")
                        .HasColumnType("bigint")
                        .HasColumnName("length");

                    b.HasNoKey();

                    b.HasIndex("InfoHash")
                        .HasDatabaseName("idx_torrent_files_info_hash");

                    b.HasIndex("PathText")
                        .HasDatabaseName("idx_torrent_files_path");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PathText"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("PathText"), new[] { "gin_trgm_ops" });

                    b.ToTable("torrent_files", (string)null);
                });

            modelBuilder.Entity("Cherry.Domain.Entities.TorrentRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("info_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("InfoHash")
                        .HasDatabaseName("idx_torrent_requests_hash");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_torrent_requests_status");

                    b.ToTable("torrent_requests", (string)null);
                });

            modelBuilder.Entity("Cherry.Domain.Entities.Torrent", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
